### ISSUE TITLE
Calling VsDocument .GetDocumentContentAsStringAsync(); Results in the following error

### ISSUE THREAD

**Issue by sgiffinlcd** [CodeFactoryLLC/CodeFactory#23]
This bug was originally created on the internal runtime repository by @jhannahLCD . Moving here to track.

The following is the captured exception for the codefactory log files.

2020/08/19 21:36:02.113|CodeFactory.VisualStudio.Integration.Services.Document.InvisibleEditorContainer|Error|LoadEditorAsync|150|The following unhandled exception occured while adding the document content. Will throw a document exception.|System.InvalidCastException: The Extender Provider failed to return an Extender for this object.
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
at CodeFactory.VisualStudio.Integration.Services.Document.InvisibleEditorContainer.92.7()

**Comment by sgiffinlcd** [comment]
@jhannahLCD 
This currently is an intermittent failure when calling a targeted com library. 
I have not been able to recreate this bug.
Adding additional guard code to make sure Com reference counter is deference in a tighter fashion.
